// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVFItPXcWPa_Za0W7rzoONaRp4oSQ4rI',
    appId: '1:1043381828948:web:ab8dddf87f83ffb1b89cc1',
    messagingSenderId: '1043381828948',
    projectId: 'global-tchat-flutter-app',
    authDomain: 'global-tchat-flutter-app.firebaseapp.com',
    storageBucket: 'global-tchat-flutter-app.appspot.com',
    measurementId: 'G-K1S38SDK2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7XEismoH_zisO9S6PqHQ4b35qb3a490',
    appId: '1:1043381828948:android:9df770a8e70d7e93b89cc1',
    messagingSenderId: '1043381828948',
    projectId: 'global-tchat-flutter-app',
    storageBucket: 'global-tchat-flutter-app.appspot.com',
  );
}
